# Generated by Django 4.2.3 on 2023-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docs',
            old_name='checked',
            new_name='page_html',
        ),
    ]
